### ISSUE TITLE
Unicode Normalization not appropriate for ASCII-8BIT

### ISSUE THREAD

**Issue by jaysoffian** [knu/ruby-domain_name#23]
Removing `unf` seems to have broken normalization. I'm seeing this with `fastlane`, but I don't think it's due to anything in particular that fastlane is doing. Here's the stacktrace:

```
/opt/homebrew/Cellar/ruby@3.1/3.1.4/lib/ruby/3.1.0/unicode_normalize/normalize.rb:141:in `normalize'
./vendor/bundle/ruby/3.1.0/gems/domain_name-0.6.20231109/lib/domain_name.rb:288:in `unicode_normalize'
./vendor/bundle/ruby/3.1.0/gems/domain_name-0.6.20231109/lib/domain_name.rb:288:in `normalize'
./vendor/bundle/ruby/3.1.0/gems/domain_name-0.6.20231109/lib/domain_name.rb:99:in `initialize'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie.rb:553:in `new'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie.rb:553:in `acceptable_from_uri?'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie.rb:591:in `valid_for_uri?'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:78:in `block (3 levels) in each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:74:in `delete_if'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:74:in `block (2 levels) in each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:72:in `each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:72:in `block in each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:71:in `each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:71:in `each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:163:in `each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:131:in `each'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:131:in `sort'
./vendor/bundle/ruby/3.1.0/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:131:in `cookies'
./vendor/bundle/ruby/3.1.0/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:12:in `call'
./vendor/bundle/ruby/3.1.0/gems/faraday_middleware-1.2.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
./vendor/bundle/ruby/3.1.0/gems/faraday_middleware-1.2.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
./vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/rack_builder.rb:154:in `build_response'
./vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/connection.rb:516:in `run_request'
./vendor/bundle/ruby/3.1.0/gems/faraday-1.10.3/lib/faraday/connection.rb:202:in `get'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:937:in `block in send_request'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:695:in `with_retry'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:936:in `send_request'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:780:in `request'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/upgrade_2fa_later_client.rb:27:in `try_upgrade_2fa_later'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:542:in `send_shared_login_request'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/portal/portal_client.rb:29:in `send_login_request'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:862:in `do_login'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:394:in `login'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/client.rb:355:in `login'
./vendor/bundle/ruby/3.1.0/gems/fastlane-2.217.0/spaceship/lib/spaceship/portal/spaceship.rb:25:in `login'
```

Where `normalize.rb`  is:
```ruby
  def self.normalize(string, form = :nfc)
    encoding = string.encoding
    case encoding
    when Encoding::UTF_8
      case form
      when :nfc then
        string.gsub REGEXP_C, NF_HASH_C
      when :nfd then
        string.gsub REGEXP_D, NF_HASH_D
      when :nfkc then
        string.gsub(REGEXP_K, KOMPATIBLE_TABLE).gsub(REGEXP_C, NF_HASH_C)
      when :nfkd then
        string.gsub(REGEXP_K, KOMPATIBLE_TABLE).gsub(REGEXP_D, NF_HASH_D)
      else
        raise ArgumentError, "Invalid normalization form #{form}."
      end
    when Encoding::US_ASCII
      string
    when *UNICODE_ENCODINGS
      normalize(string.encode(Encoding::UTF_8), form).encode(encoding)
    else
      raise Encoding::CompatibilityError, "Unicode Normalization not appropriate for #{encoding}"
    end
  end
```

Line 141 is raising the `Encoding::CompatibilityError` with "Unicode Normalization not appropriate for ASCII-8BIT".

**Comment by jocel1** [comment]
I've exactly the same issue, using RestClient 2.1.0

```
class EventbriteApi
  BASE_URL = "https://www.eventbriteapi.com/v3"
  ORGANIZATION_ID = "142062802932"

  def self.get_events(params)
    url = "#{BASE_URL}/organizations/#{ORGANIZATION_ID}/events?expand=venue"
    begin
      RestClient.get(url)
    rescue RestClient::ExceptionWithResponse => e
      e.response
    end
  end
```

Calling get_events will return:

Encoding::CompatibilityError - Unicode Normalization not appropriate for ASCII-8BIT:
  app/lib/eventbrite_api.rb:11:in `get_events'
  app/controllers/api/v4/events_controller.rb:11:in `index'
  lib/rack_x_robots_tag.rb:8:in `call'
  test/test_helper.rb:776:in `events'
  test/controllers/api/v4/events_controller_test.rb:5:in `block in <class:EventsControllerTest>'

No issue with domain_name 0.5.20190701

**Comment by jgarber-cisco** [comment]
Same issue with one of our internal gems that depends on faraday:

```
	28: from /Users/jagarber/.rubies/ruby-2.7.6/lib/ruby/2.7.0/forwardable.rb:235:in `get'
	27: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday-1.10.2/lib/faraday/connection.rb:202:in `get'
	26: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday-1.10.2/lib/faraday/connection.rb:516:in `run_request'
	25: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday-1.10.2/lib/faraday/rack_builder.rb:154:in `build_response'
	24: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday-1.10.2/lib/faraday/middleware.rb:18:in `call'
	23: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:67:in `call'
	22: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:81:in `perform_with_redirection'
	21: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday-1.10.2/lib/faraday/response.rb:61:in `on_complete'
	20: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:87:in `block in perform_with_redirection'
	19: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:79:in `perform_with_redirection'
	18: from /Users/jagarber/.gem/ruby/2.7.6/gems/faraday-cookie_jar-0.0.7/lib/faraday/cookie_jar.rb:12:in `call'
	17: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:131:in `cookies'
	16: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:131:in `sort'
	15: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:131:in `each'
	14: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:163:in `each'
	13: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:71:in `each'
	12: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:71:in `each'
	11: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:72:in `block in each'
	10: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:72:in `each'
	 9: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:74:in `block (2 levels) in each'
	 8: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:74:in `delete_if'
	 7: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie_jar/hash_store.rb:78:in `block (3 levels) in each'
	 6: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie.rb:591:in `valid_for_uri?'
	 5: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie.rb:553:in `acceptable_from_uri?'
	 4: from /Users/jagarber/.gem/ruby/2.7.6/gems/http-cookie-1.0.5/lib/http/cookie.rb:553:in `new'
	 3: from /Users/jagarber/.gem/ruby/2.7.6/gems/domain_name-0.6.20231109/lib/domain_name.rb:99:in `initialize'
	 2: from /Users/jagarber/.gem/ruby/2.7.6/gems/domain_name-0.6.20231109/lib/domain_name.rb:290:in `normalize'
	 1: from /Users/jagarber/.gem/ruby/2.7.6/gems/domain_name-0.6.20231109/lib/domain_name.rb:290:in `unicode_normalize'
/Users/jagarber/.rubies/ruby-2.7.6/lib/ruby/2.7.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
```

**Comment by honzasterba** [comment]
same here, resulted in monkey patching faraday for the time being

**Comment by taylorbrooks** [comment]
Same on Faraday.

**Comment by tisba** [comment]
I'm the maintainer of faraday-follow-redirects gem and trying to address/fix https://github.com/tisba/faraday-follow-redirects/issues/7#issue-2029202022 related to this issue.

In v0.5.20190701 `DomainName.normalize` (https://github.com/knu/ruby-domain_name/blob/v0.5.20190701/lib/domain_name.rb#L285-L291) was using unf (https://github.com/knu/ruby-unf) `String#to_nfc` which does return self, if `String#ascii_only?`. This behaviour changed with the current released version, as now there is always the assumption that the input to `DomainName.normalize` is unicode.

I'll give it a try to restore the original behaviour.
